# -*- coding: utf-8 -*-
"""MEJ-Prisonniers.ipynb

Automatically generated by Colaboratory.
"""

import random
from random import randint

board = [[0,1],
         [10,11]]

checkers = [[0,0],
          [0,0]]

FinalValues = "Values: "

def initialise_board():
  for i in range(len(board)):
    for j in range(len(board[0])):
      value = randint(0,1)
      if value == 1:
         checkers[i][j] = 1;

initialise_board()
checkers

def display_values():
    Values = [0, 0, 0, 0]
    count = 0;
    for i in range(len(board)):
      for j in range(len(board[0])):
        if checkers[i][j] == 1:
          Values[count] = board[i][j]
        count += 1;
    return Values

finalBoard = display_values()
finalBoard

unité = 0
dizaine = 0
for i in range(len(finalBoard)):
  if finalBoard[i] != 0:
    if finalBoard[i] < 10:
      unité += 1
    elif finalBoard[i] >= 10:
      dizaine += 1

if unité%2 == 0:
  unité =0

if dizaine&2 == 0:
  dizaine = 0

caseRaw = str(unité) + str(dizaine)
case = 0

if int(caseRaw) == 0:
  case = 1

if int(caseRaw) == 1:
  case = 2

if int(caseRaw) == 10:
  case = 3

if int(caseRaw) == 11:
  case = 4

case
